# system python interpreter. used only to create virtual environment
PY = python3
VENV = .env
BIN=$(VENV)/bin

# make it work on windows too
ifeq ($(OS), Windows_NT)
	BIN=$(VENV)/Scripts
	PY=python
endif

all: venv run

venv:
	: # Create venv if it doesn't exist
	test -d $(VENV) || ($(PY) -m venv $(VENV) && $(BIN)/pip install -r requirements.txt)

install:
	. $(BIN)/activate && pip install -r requirements.txt

examples-install:
	. $(BIN)/activate && pip install -r examples/requirements.txt

develop: venv
	. $(BIN)/activate && maturin develop

build: venv
	. $(BIN)/activate && maturin build

run: develop
	. $(BIN)/activate && ./examples/ngrok-http-minimal.py

runaio: develop examples-install
	. $(BIN)/activate && python ./examples/aiohttp-ngrok.py

rundjango: develop examples-install
	. $(BIN)/activate && python ./examples/django-single-file.py

# Run django using the manage.py which is auto-generated by "django-admin startproject"
# The manage.py file has the ngrok tunnel setup code.
rundjangosite: develop examples-install
	. $(BIN)/activate && python ./examples/djangosite/manage.py runserver localhost:1234

# Run django ASGI via uvicorn. The asgi.py file has the ngrok tunnel setup code.
rundjangouvi: develop examples-install
	. $(BIN)/activate && pushd ./examples/djangosite && python -m uvicorn djangosite.asgi:application

# Run django ASGI via gunicorn. The asgi.py file has the ngrok tunnel setup code.
rundjangoguni: develop examples-install
	. $(BIN)/activate && pushd ./examples/djangosite && python -m gunicorn djangosite.asgi:application -k uvicorn.workers.UvicornWorker

runflask: develop examples-install
	. $(BIN)/activate && python ./examples/flask-ngrok.py

runfull: develop
	. $(BIN)/activate && ./examples/ngrok-http-full.py

runlabeled: develop
	. $(BIN)/activate && ./examples/ngrok-labeled.py

runtcp: develop
	. $(BIN)/activate && ./examples/ngrok-tcp.py

runtls: develop
	. $(BIN)/activate && ./examples/ngrok-tls.py

runuvi: develop examples-install
	. $(BIN)/activate && python ./examples/uvicorn-ngrok.py

# e.g.: make test=TestNgrok.test_gzip_tunnel test
test: develop
	. $(BIN)/activate && python ./test/test.py $(test)

# e.g.: make test=TestNgrok.test_gzip_tunnel testonly
testonly:
	. $(BIN)/activate && python ./test/test.py $(test)

# testfast is called by github workflow in ci.yml
testfast: develop
	. $(BIN)/activate && py.test -n 4 ./test/test.py

testpublish:
	. $(BIN)/activate && maturin publish --repository testpypi

docs: develop black
	. $(BIN)/activate && sphinx-build -b html doc_source/ docs/

black: develop
	. $(BIN)/activate && black examples

clean:
	rm -rf $(VENV) target/
